### ISSUE TITLE
Library dosent work for me 

### ISSUE THREAD

**Issue by Hideaki974** [BlenderPro/BlenderPro#12]
Traceback (most recent call last):
  File "/home/hideaki/.config/blender/2.79/scripts/startup/bl_app_templates_user/BlenderPro-master/library/object_library.py", line 329, in execute
    subprocess.call(bpy.app.binary_path + ' "' + utils_library.get_thumbnail_file_path() + '" -b --python "' + thumbnail_script_path + '"')   
  File "/home/hideaki/soft/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/hideaki/soft/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/home/hideaki/soft/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hideaki/soft/blender-2.79b-linux-glibc219-x86_64/blender "/home/hideaki/.config/blender/2.79/scripts/startup/bl_app_templates_user/BlenderPro-master/library/thumbnail.blend" -b --python "/home/hideaki/Documents/RGSS/models/lib_test/tmp/blender_fb60ZC/thumb_temp.py"'

location: <unknown location>:-1

i'm so new in all off this so i dont really get it but a hot it can help

**Comment by Hideaki974** [comment]
i work on Ubuntu 15.04
